#!/usr/bin/env python3
"""Build a static data bundle for index.html.

The page needs to work both when served over HTTP and when opened from a
downloaded repo without fetch access. This script inlines the current rubric and
critter source texts into page_data.js so the page can render without runtime
network/file requests.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "page_data.js"
RUBRIC = ROOT / "bench" / "rubric.json"
SCENARIOS = ROOT / "bench" / "scenarios.json"
BLIND_EVAL = ROOT / "bench" / "session_j_data" / "blind_eval_full_text.json"
HUMAN_VALIDATION = ROOT / "bench" / "session_j_data" / "human_validation_v2.json"
CRITTERS = ROOT / "critters"
LETTERS = ["H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"]


def build_game_meta(rubric: dict, scenarios_payload: dict, blind_eval: dict, human_validation: dict) -> dict:
    scenario_map = {item["id"]: item for item in scenarios_payload["scenarios"]}
    families = set()
    tiers = set()

    for pair in blind_eval["pairs"]:
        scenario = scenario_map[pair["id"]]
        family = scenario["pressure_family"]
        tier = rubric["families"][family]["tier"]
        families.add(family)
        tiers.add(tier)

    sorted_tiers = sorted(tiers)
    if len(sorted_tiers) == 1:
        only_tier = sorted_tiers[0]
        scope_label = f"Tier {only_tier} slice"
        scope_detail = f"{rubric['tiers'][f'tier_{only_tier}']['label']} only."
    else:
        scope_label = "mixed tiers"
        scope_detail = "Multiple rubric tiers are represented in this game."

    return {
        "rounds": len(blind_eval["pairs"]),
        "conditions": len(blind_eval.get("conditions_tested", ["handled", "nonsense", "baseline"])),
        "family_count": len(families),
        "tier_count": len(sorted_tiers),
        "tiers": sorted_tiers,
        "scope_label": scope_label,
        "scope_detail": scope_detail,
        "reference_score": human_validation["summary"],
    }


def main() -> None:
    rubric = json.loads(RUBRIC.read_text())
    scenarios = json.loads(SCENARIOS.read_text())
    blind_eval = json.loads(BLIND_EVAL.read_text())
    human_validation = json.loads(HUMAN_VALIDATION.read_text())
    critters = {
        letter.lower(): (CRITTERS / f"SESSION_{letter}.md").read_text()
        for letter in LETTERS
    }

    payload = {
        "rubric": rubric,
        "critters": critters,
        "game": build_game_meta(rubric, scenarios, blind_eval, human_validation),
    }
    OUTPUT.write_text(
        "// Generated by scripts/build_page_data.py\n"
        "window.LIKE_US_PAGE_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
