#!/usr/bin/env python3
"""Build a static data bundle for index.html.

The page needs to work both when served over HTTP and when opened from a
downloaded repo without fetch access. This script inlines the current rubric and
critter source texts into page_data.js so the page can render without runtime
network/file requests.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "page_data.js"
RUBRIC = ROOT / "bench" / "rubric.json"
CRITTERS = ROOT / "critters"
LETTERS = ["H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"]


def main() -> None:
    rubric = json.loads(RUBRIC.read_text())
    critters = {
        letter.lower(): (CRITTERS / f"SESSION_{letter}.md").read_text()
        for letter in LETTERS
    }

    payload = {"rubric": rubric, "critters": critters}
    OUTPUT.write_text(
        "// Generated by scripts/build_page_data.py\n"
        "window.LIKE_US_PAGE_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
